name: Build and push base image 

on:

  push:
    branches:
      - main

  # Run every Sunday at 0:00 UTC    
  schedule:
  - cron: 0 0 * * SUN

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@main
    
    - uses: docker/login-action@v2 
      with:
        username: ${{ secrets.dockerhub_user }}
        password: ${{ secrets.dockerhub_access_token }}

    - uses: docker/setup-buildx-action@v1
    - uses: docker/setup-qemu-action@v1
    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build container
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: Dockerfile
        tags: digichef/php8.1-nginx:1.0
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
